#!/usr/bin/python
# encoding: utf-8

"""
Attempt to read the contents of a .textexpander plist file, and generate a new file with the user's abbreviations of choice.
"""

import plistlib
import sys
import os.path

# Extract folder and filename
infile = sys.argv[1]
basename, extension = os.path.splitext(infile)

# Make sure it's a TextExpander file.
if extension != '.textexpander':
    print("%s is not a TextExpander file." % infile)
    sys.exit(-1)

# Generate the new filename.
outfile = basename + "-2" + extension

# Parse the snippet file.
try:
    te = plistlib.readPlist(infile)
except IOError:
    print("Couldn't open %s to read from." % infile)
    sys.exit(-1)

# Go through the snippets, allowing the user to change each abbreviation.
for i in range(len(te['snippetsTE2'])):
    print 'Label: ' + te['snippetsTE2'][i]['label']
    newabbrev = raw_input(
            'Abbreviation [' + te['snippetsTE2'][i]['abbreviation'] + ']: ')
    if newabbrev != '':
        te['snippetsTE2'][i]['abbreviation'] = newabbrev
    print

# Write out the new .textexpander file.
try:
    plistlib.writePlist(te, outfile)
    print "wrote:", outfile
except IOError:
    print "Couldn't write new textexpander file", outfile
    sys.exit(-1)

