#!/usr/bin/python

import plistlib
import sys
import os.path

# Get the TextExpander snippet filename and the prefix from the command line.
fn = os.path.abspath(sys.argv[1])
prefix = sys.argv[2]

# Extract the parts of the filename.
folder = os.path.dirname(fn)
fnbase = os.path.basename(fn)

# Make sure it's a TextExpander file.
if fnbase[-13:] != '.textexpander':
  sys.exit(fnbase + " is not a TextExpander file.")

# Generate the .tedlist filename.
tedist = folder + '/' + fnbase[:-13] + '.tedist'

# Parse the snippet file.
te = plistlib.readPlist(fn)

# Go through the snippets, replacing each prefix with [[PREFIX]].
for i in range(len(te['snippetsTE2'])):
  prelength = len(prefix)
  if te['snippetsTE2'][i]['abbreviation'][0:prelength] == prefix:
    te['snippetsTE2'][i]['abbreviation'] = '[[PREFIX]]' + \
                                            te['snippetsTE2'][i]['abbreviation'][prelength:]

# Write out the new .tedist file.
plistlib.writePlist(te, tedist)
